Repository agnesoft/adev, pull requests merged in 2020-07, with the labels that each got.

#139 Add persistent vector #138
  CMakeLists.txt
  projects/ACore/include/ACore/DataStreamBase.hpp
  projects/ACore/test/DataStreamTest.cpp
  projects/AFile/include/AFile.hpp
  projects/AFile/include/AFile/PersistentVector.hpp
  projects/AFile/test/FileStreamTest.cpp
  projects/AFile/test/PersistentVectorTest.cpp
Labels: feature

#144 Remove load value from file #143
  projects/AFile/PersistentDictionaryData.cpp
  projects/AFile/include/AFile/File.hpp
  projects/AFile/include/AFile/PersistentVector.hpp
  projects/AFile/test/FileTest.cpp
  projects/AFile/test/PersistentVectorTest.cpp
Labels: enhancement

#146 DictionaryBase-throws-exception-when-getting-missing-value-#145
  projects/ACore/include/ACore/DictionaryBase.hpp
  projects/ACore/test/DictionaryTest.cpp
  projects/AFile/PersistentDictionaryData.cpp
  projects/AFile/test/PersistentDictionaryTest.cpp
Labels: enhancement

#153 Use Ubuntu 20.04
  .github/workflows/ADev.yml
  build.sh
Labels: enhancement

#155 Update README.md
  README.md
Labels: enhancement

#159 Add ADbStudio
  projects/ADbStudio/.gitignore
  projects/ADbStudio/README.md
  projects/ADbStudio/babel.config.js
  projects/ADbStudio/package-lock.json
  projects/ADbStudio/package.json
  projects/ADbStudio/public/favicon.ico
  projects/ADbStudio/public/index.html
  projects/ADbStudio/src/App.vue
  projects/ADbStudio/src/assets/logo.png
  projects/ADbStudio/src/components/HelloWorld.vue
  projects/ADbStudio/src/main.js
Labels: feature

#161 Add a db studio to build #160
  .github/workflows/ADev.yml
  README.md
  build.sh
  projects/ADbStudio/.gitignore
  projects/ADbStudio/jest.config.js
  projects/ADbStudio/package-lock.json
  projects/ADbStudio/package.json
  projects/ADbStudio/tests/unit/main.spec.js
Labels: feature

#164 Added Plugins
  projects/ADbStudio/.env
  projects/ADbStudio/cypress.json
  projects/ADbStudio/package-lock.json
  projects/ADbStudio/package.json
  projects/ADbStudio/src/App.vue
  projects/ADbStudio/src/i18n.js
  projects/ADbStudio/src/locales/en.json
  projects/ADbStudio/src/main.js
  projects/ADbStudio/src/plugins/axios.js
  projects/ADbStudio/src/router/index.js
  projects/ADbStudio/src/store/index.js
  projects/ADbStudio/src/views/About.vue
  projects/ADbStudio/src/views/Home.vue
  projects/ADbStudio/tests/e2e/.eslintrc.js
  projects/ADbStudio/tests/e2e/plugins/index.js
  projects/ADbStudio/tests/e2e/specs/test.js
  projects/ADbStudio/tests/e2e/support/commands.js
  projects/ADbStudio/tests/e2e/support/index.js
  projects/ADbStudio/tests/unit/main.spec.js
  projects/ADbStudio/vue.config.js
Labels: feature

#165 Add path search #163
  CMakeLists.txt
  projects/AGraph/include/AGraph.hpp
  projects/AGraph/include/AGraph/BreadthFirstSearch.hpp
  projects/AGraph/include/AGraph/DepthFirstSearch.hpp
  projects/AGraph/include/AGraph/GraphSearch.hpp
  projects/AGraph/include/AGraph/PathSearch.hpp
  projects/AGraph/test/BreadthFirstSearchTest.cpp
  projects/AGraph/test/DepthFirstSearchTest.cpp
  projects/AGraph/test/PathSearchTest.cpp
Labels: feature

#167 Created Main Layout
  projects/ADbStudio/src/App.vue
  projects/ADbStudio/src/components/layout/MainFooter.vue
  projects/ADbStudio/src/components/layout/MainHeader.vue
  projects/ADbStudio/src/main.js
  projects/ADbStudio/tests/unit/TestUtils.js
  projects/ADbStudio/tests/unit/layout/MainFooter.spec.js
  projects/ADbStudio/tests/unit/layout/MainHeader.spec.js
  projects/ADbStudio/tests/unit/main.spec.js
Labels: feature

#171 Add string_view support
  projects/ACore/include/ACore/DataStreamBase.hpp
  projects/ACore/include/ACore/Variant.hpp
  projects/ACore/test/DataStreamTest.cpp
  projects/ACore/test/VariantTest.cpp
Labels: enhancement

#172 Add database value #169
  CMakeLists.txt
  projects/ACore/include/ACore/Variant.hpp
  projects/ADb/Value.cpp
  projects/ADb/include/ADb.hpp
  projects/ADb/include/ADb/ADbModule.hpp
  projects/ADb/include/ADb/Value.hpp
  projects/ADb/pch.hpp
  projects/ADb/test/ValueTest.cpp
  projects/ADb/test/pch.hpp
Labels: feature

#174 Add missing nodiscard
  projects/ACore/include/ACore/Variant.hpp
Labels: bug

#176 Add adb::KeyValue
  CMakeLists.txt
  README.md
  projects/ADb/README.md
  projects/ADb/include/ADb.hpp
  projects/ADb/include/ADb/KeyValue.hpp
  projects/ADb/test/KeyValueTest.cpp
Labels: feature

#178 Create main scene #168
  projects/ADbStudio/package-lock.json
  projects/ADbStudio/src/components/scene/ADbView.vue
  projects/ADbStudio/src/components/scene/Edge.vue
  projects/ADbStudio/src/components/scene/Node.vue
  projects/ADbStudio/src/components/scene/SearchField.vue
  projects/ADbStudio/src/locales/cz.json
  projects/ADbStudio/src/locales/en.json
  projects/ADbStudio/src/router/index.js
  projects/ADbStudio/src/store/index.js
  projects/ADbStudio/src/store/modules/scene.js
  projects/ADbStudio/src/views/Scene.vue
  projects/ADbStudio/tests/unit/scene/AdbView.spec.js
  projects/ADbStudio/tests/unit/scene/Edge.spec.js
  projects/ADbStudio/tests/unit/scene/Node.spec.js
  projects/ADbStudio/tests/unit/store/scene.spec.js
  projects/ADbStudio/tests/unit/views/scene.spec.js
Labels: feature
