Repository agnesoft/adev, pull requests merged in 2020-08, with the labels that each got.

#180 Zoom in view #179
  projects/ADbStudio/src/components/scene/ADbView.vue
  projects/ADbStudio/src/locales/cz.json
  projects/ADbStudio/src/locales/en.json
  projects/ADbStudio/src/views/Scene.vue
Labels: feature

#185 Fixed resizing
  projects/ADbStudio/src/views/Scene.vue
Labels: bug

#189 Create and use base button #186
  projects/ADbStudio/src/App.vue
  projects/ADbStudio/src/components/base/BaseButton.vue
  projects/ADbStudio/src/main.js
  projects/ADbStudio/src/views/Scene.vue
  projects/ADbStudio/tests/unit/TestUtils.js
  projects/ADbStudio/tests/unit/base/BaseButton.spec.js
Labels: feature

#193 Create search field #190
  projects/ADbStudio/src/App.vue
  projects/ADbStudio/src/assets/images/icons.svg
  projects/ADbStudio/src/components/base/BaseButton.vue
  projects/ADbStudio/src/components/scene/SearchField.vue
  projects/ADbStudio/src/components/transitions/SlideXTransition.vue
  projects/ADbStudio/src/locales/cz.json
  projects/ADbStudio/src/locales/en.json
  projects/ADbStudio/src/main.js
  projects/ADbStudio/src/views/Scene.vue
  projects/ADbStudio/tests/unit/scene/SearchField.spec.js
  projects/ADbStudio/tests/unit/transitions/SlideXTransition.spec.js
Labels: feature

#197 Show list of nodes, list of edges and raw data #194
  projects/ADbStudio/src/assets/images/icons.svg
  projects/ADbStudio/src/components/base/BaseButton.vue
  projects/ADbStudio/src/components/base/BaseIcon.vue
  projects/ADbStudio/src/components/scene/EdgeListData.vue
  projects/ADbStudio/src/components/scene/LeftPanel.vue
  projects/ADbStudio/src/components/scene/ListData.vue
  projects/ADbStudio/src/components/scene/NodeListData.vue
  projects/ADbStudio/src/components/scene/RawData.vue
  projects/ADbStudio/src/locales/cz.json
  projects/ADbStudio/src/locales/en.json
  projects/ADbStudio/src/store/modules/scene.js
  projects/ADbStudio/src/views/Scene.vue
  projects/ADbStudio/tests/unit/TestUtils.js
  projects/ADbStudio/tests/unit/scene/AdbView.spec.js
  projects/ADbStudio/tests/unit/scene/EdgeListData.spec.js
  projects/ADbStudio/tests/unit/scene/LeftPanel.spec.js
  projects/ADbStudio/tests/unit/scene/ListData.spec.js
  projects/ADbStudio/tests/unit/scene/NodeListData.spec.js
  projects/ADbStudio/tests/unit/scene/RawData.spec.js
  projects/ADbStudio/tests/unit/views/scene.spec.js
Labels: feature

#199 Add subquery
  projects/ADb/Query.cpp
  projects/ADb/include/ADb/Query.hpp
  projects/ADb/test/QueryTest.cpp
Labels: feature

#201 Search elements in ADbView
  projects/ADbStudio/src/components/base/BaseButton.vue
  projects/ADbStudio/src/components/base/BaseIcon.vue
  projects/ADbStudio/src/components/base/BaseMessage.vue
  projects/ADbStudio/src/components/scene/ADbView.vue
  projects/ADbStudio/src/components/scene/Edge.vue
  projects/ADbStudio/src/components/scene/Node.vue
  projects/ADbStudio/src/components/scene/SearchField.vue
  projects/ADbStudio/src/components/transitions/FadeTransition.vue
  projects/ADbStudio/src/locales/cz.json
  projects/ADbStudio/src/locales/en.json
  projects/ADbStudio/src/store/modules/scene.js
  projects/ADbStudio/src/views/Scene.vue
  projects/ADbStudio/tests/unit/TestUtils.js
  projects/ADbStudio/tests/unit/base/BaseMessage.spec.js
  projects/ADbStudio/tests/unit/scene/SearchField.spec.js
  projects/ADbStudio/tests/unit/transitions/FadeTransition.spec.js
  projects/ADbStudio/tests/unit/views/scene.spec.js
Labels: feature

#203 Display node/edge data on hover #202
  projects/ADbStudio/src/components/scene/ADbView.vue
  projects/ADbStudio/src/components/scene/Edge.vue
  projects/ADbStudio/src/components/scene/EdgeListData.vue
  projects/ADbStudio/src/components/scene/Element.vue
  projects/ADbStudio/src/components/scene/ElementData.vue
  projects/ADbStudio/src/components/scene/LeftPanel.vue
  projects/ADbStudio/src/components/scene/ListData.vue
  projects/ADbStudio/src/components/scene/Node.vue
  projects/ADbStudio/src/components/scene/NodeListData.vue
  projects/ADbStudio/src/locales/cz.json
  projects/ADbStudio/src/locales/en.json
  projects/ADbStudio/src/store/modules/scene.js
  projects/ADbStudio/src/views/Scene.vue
  projects/ADbStudio/tests/unit/TestUtils.js
  projects/ADbStudio/tests/unit/scene/Edge.spec.js
  projects/ADbStudio/tests/unit/scene/Element.spec.js
  projects/ADbStudio/tests/unit/scene/ElementData.spec.js
  projects/ADbStudio/tests/unit/scene/ListData.spec.js
  projects/ADbStudio/tests/unit/scene/Node.spec.js
  projects/ADbStudio/tests/unit/views/scene.spec.js
Labels: feature

#208 Disable-sanitize-memory-check-#206
  .github/workflows/ADev.yml
Labels: enhancement

#207 Fix-Sanitize-memory-sometimes-fail-#206
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
  .github/workflows/ADev.yml
  CMakeLists.txt
  build.sh
Labels: bug

#215 Fix templates placeholders #214
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
Labels: bug

#213 Add insert edge #209
  CMakeLists.txt
  projects/ADb/InsertEdgeFromQuery.cpp
  projects/ADb/InsertEdgeQuery.cpp
  projects/ADb/InsertQuery.cpp
  projects/ADb/SelectQuery.cpp
  projects/ADb/include/ADb/InsertEdgeFromQuery.hpp
  projects/ADb/include/ADb/InsertEdgeQuery.hpp
  projects/ADb/include/ADb/InsertQuery.hpp
  projects/ADb/include/ADb/Placeholders.hpp
  projects/ADb/include/ADb/Query.hpp
  projects/ADb/include/ADb/QueryData.hpp
  projects/ADb/include/ADb/SelectQuery.hpp
  projects/ADb/test/InsertEdgeQueryTest.cpp
  projects/ADb/test/InsertEdgesQueryTest.cpp
  projects/ADb/test/InsertNodeQueryTest.cpp
  projects/ADb/test/InsertNodesQueryTest.cpp
  projects/ADb/test/InsertQueryTest.cpp
  projects/ADb/test/QueryTest.cpp
Labels: feature

#217 Improve main readme #216
  README.md
Labels: enhancement

#219 Fit readme ci table to page #218
  README.md
Labels: documentation, enhancement

#220 Show node/edge data on click #212
  projects/ADbStudio/src/components/base/BaseBox.vue
  projects/ADbStudio/src/components/scene/Element.vue
  projects/ADbStudio/src/components/scene/Elements.vue
  projects/ADbStudio/src/components/scene/RightPanel.vue
  projects/ADbStudio/src/locales/cz.json
  projects/ADbStudio/src/locales/en.json
  projects/ADbStudio/src/store/modules/scene.js
  projects/ADbStudio/src/views/Scene.vue
  projects/ADbStudio/tests/unit/TestUtils.js
  projects/ADbStudio/tests/unit/scene/Element.spec.js
  projects/ADbStudio/tests/unit/scene/Elements.spec.js
  projects/ADbStudio/tests/unit/scene/RightPanel.spec.js
  projects/ADbStudio/tests/unit/store/scene.spec.js
  projects/ADbStudio/tests/unit/views/scene.spec.js
Labels: feature

#222 Fix hover on edge #221
  projects/ADbStudio/src/components/scene/Edge.vue
  projects/ADbStudio/src/components/scene/Elements.vue
  projects/ADbStudio/src/views/Scene.vue
Labels: bug

#230 Benchmark sometimes fail on mac os #182
  .github/workflows/ADev.yml
  CMakeLists.txt
  README.md
  build.sh
  projects/ABenchmarks/DataIndexMapBenchmark.cpp
  projects/ABenchmarks/README.md
  projects/ABenchmarks/VariantBenchmark.cpp
  projects/ABenchmarks/pch.hpp
Labels: bug

#234 Added snapshot testing
  projects/ADbStudio/tests/unit/layout/MainFooter.spec.js
  projects/ADbStudio/tests/unit/layout/MainHeader.spec.js
  projects/ADbStudio/tests/unit/layout/__snapshots__/MainFooter.spec.js.snap
  projects/ADbStudio/tests/unit/layout/__snapshots__/MainHeader.spec.js.snap
  projects/ADbStudio/tests/unit/scene/AdbView.spec.js
  projects/ADbStudio/tests/unit/scene/DataWrapper.spec.js
  projects/ADbStudio/tests/unit/scene/Edge.spec.js
  projects/ADbStudio/tests/unit/scene/EdgeListData.spec.js
  projects/ADbStudio/tests/unit/scene/LeftPanel.spec.js
  projects/ADbStudio/tests/unit/scene/Node.spec.js
  projects/ADbStudio/tests/unit/scene/NodeListData.spec.js
  projects/ADbStudio/tests/unit/scene/RightPanel.spec.js
  projects/ADbStudio/tests/unit/scene/__snapshots__/AdbView.spec.js.snap
  projects/ADbStudio/tests/unit/scene/__snapshots__/DataWrapper.spec.js.snap
  projects/ADbStudio/tests/unit/scene/__snapshots__/Edge.spec.js.snap
  projects/ADbStudio/tests/unit/scene/__snapshots__/EdgeListData.spec.js.snap
  projects/ADbStudio/tests/unit/scene/__snapshots__/LeftPanel.spec.js.snap
  projects/ADbStudio/tests/unit/scene/__snapshots__/Node.spec.js.snap
  projects/ADbStudio/tests/unit/scene/__snapshots__/NodeListData.spec.js.snap
  projects/ADbStudio/tests/unit/scene/__snapshots__/RightPanel.spec.js.snap
  projects/ADbStudio/tests/unit/views/__snapshots__/scene.spec.js.snap
  projects/ADbStudio/tests/unit/views/scene.spec.js
Labels: feature

#236 Update tiny process library #228
  projects/tiny-process-library/CMakeLists.txt
  projects/tiny-process-library/process.hpp
  projects/tiny-process-library/process_unix.cpp
  projects/tiny-process-library/process_win.cpp
  projects/tiny-process-library/tests/io_test.cpp
  projects/tiny-process-library/tests/multithread_test.cpp
  projects/tiny-process-library/tests/open_close_test.cpp
Labels: enhancement

#237 Add recursive query data binding
  projects/ADb/Query.cpp
  projects/ADb/include/ADb/Query.hpp
  projects/ADb/test/QueryTest.cpp
Labels: enhancement
